Script started on Fri, Mar 10, 2017 10:46:12 AM
]0;~
[32mVoon Shin@DESKTOP-591DIGO [33m~[0m
$ whoami; pwd
Voon Shin
/home/Voon Shin
]0;~
[32mVoon Shin@DESKTOP-591DIGO [33m~[0m
$ git config -l
core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
diff.astextplain.textconv=astextplain
rebase.autosquash=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.required=true
credential.helper=manager
user.email=lvs_0626@hotmail.com
user.name=VoonShin
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.hw1(3n+1).cpp.url=https://github.com/VoonShin/lab1.git
remote.hw1(3n+1).cpp.fetch=+refs/heads/*:refs/remotes/hw1(3n+1).cpp/*
]0;~
[32mVoon Shin@DESKTOP-591DIGO [33m~[0m
$ git clone https://github.com/VoonShin/lab1
Cloning into 'lab1'...
remote: Counting objects: 3, done.[K
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
]0;~
[32mVoon Shin@DESKTOP-591DIGO [33m~[0m
$ exit

Script done on Fri, Mar 10, 2017 10:47:01 AM
